### ISSUE TITLE
problem with connect to database running in docker container.

### ISSUE THREAD

**Issue by TayTTo** [kristijanhusak/vim-dadbod-ui#310]
Hi, I have a problem with running vim dadbod ui for connect to a database in a docker container.
First, let's me show how I connect to that database with sql command interminal.
docker-compose file
```
version: '3'
services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    volumes:
      - ./web:/app  #This help mount working directory with container volume. Allow auto reload when code change.
      - /app/node_modules  
    environment:
      - NODE_ENV=development
    scale: 3
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Linh#4321
      - MYSQL_DATABASE=testdb
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql  #This helps persist the database data even if the container is stopped or removed.
volumes:
  db:

```
just look at the db: part to see the password
And here is the result when I run `mysql -u root -p -P 3307 -h 127.0.0.1`

![Image](https://github.com/user-attachments/assets/578f1437-78ce-470d-8565-18251356c48e)

Let's first check with normal database( the database that run in my machine, not in container)

![Image](https://github.com/user-attachments/assets/0287a200-9f17-4373-b583-c19f8417dbc0)
and here is the result, it just works.

![Image](https://github.com/user-attachments/assets/028df2b9-4454-4f2d-a2e0-181cf96bbb43)

Then I tried to connect to the database in the docker container:

![Image](https://github.com/user-attachments/assets/e312de1e-4e7b-42c1-8f2b-7ac0b2147c9b)

![Image](https://github.com/user-attachments/assets/c18ec4af-5b42-46d8-aec8-1c8a1a5dbcaf)
